import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const root = new URL('..', import.meta.url);
const prompts = JSON.parse(await readFile(new URL('data/prompts.json', root), 'utf8'));
const detailsDir = new URL('details/', root);

const categories = new Map();
for (const prompt of prompts) {
  const values = categories.get(prompt.category) ?? [];
  values.push(prompt);
  categories.set(prompt.category, values);
}

function tableRows(language) {
  return [...categories.entries()].flatMap(([category, values]) => [
    `### ${category.replaceAll('-', ' ')}`,
    '',
    language === 'zh'
      ? '| 效果 | 引擎 | Prompt | 来源 |'
      : '| Effect | Engine | Prompt | Source |',
    '|---|---|---|---|',
    ...values.map((item) => {
      const effect = item.effect_summary.replaceAll('|', '/');
      const source = `[${item.source.author.name}](${item.source.url})`;
      return `| ${effect} | ${item.engines.join(' + ')} | [${language === 'zh' ? '查看并复制' : 'View and copy'}](details/${item.slug}.md) | ${source} |`;
    }),
    '',
  ]).join('\n');
}

const commonHeader = [
  '<!-- Generated by scripts/generate.mjs. Edit data/prompts.json, not this file. -->',
  '',
];

const readme = [
  ...commonHeader,
  '# Awesome 3D Prompts',
  '',
  'A source-transparent catalog of prompts that produced visible 3D results. The first collection covers **GPT-6 Astra** across Blender, browser 3D, WebGL, Three.js, games, spatial product work, and related workflows.',
  '',
  `[Browse the visual 3D Prompt Gallery on BeatAPI](https://beatapi.io/3d-prompts?utm_source=github&utm_medium=readme&utm_campaign=awesome-3d-prompts)`,
  '',
  `**Review status:** ${prompts.length} accepted cases toward a target of 50. The remaining gap is intentional: no prompt is invented to fill it.`,
  '',
  'Every entry separates the model claim, engine, exact or derived instruction, visible result, original source, author, verification date, and rights status. “GPT-6 Astra” identifies the model used in the cited workflow; it does not mean BeatAPI itself is a 3D renderer.',
  '',
  '## Prompts',
  '',
  tableRows('en'),
  '## Contributing',
  '',
  'Read [CONTRIBUTING.md](CONTRIBUTING.md). New entries need a public source, a copyable prompt or agent instruction, an explicit model claim, and a visible result.',
  '',
  '## Rights',
  '',
  'The MIT license covers this repository’s original tooling and editorial structure only. Source prompts and media retain their original rights; see [RIGHTS.md](RIGHTS.md).',
  '',
].join('\n');

const readmeZh = [
  ...commonHeader,
  '# Awesome 3D Prompts 中文版',
  '',
  '一个强调来源透明的 3D Prompt 合集。首期聚焦 **GPT-6 Astra**，覆盖 Blender、浏览器 3D、WebGL、Three.js、游戏、空间化产品展示与相关工作流。',
  '',
  `[在 BeatAPI 浏览可视化 3D Prompt 合集](https://beatapi.io/zh/3d-prompts?utm_source=github&utm_medium=readme&utm_campaign=awesome-3d-prompts)`,
  '',
  `**审核状态：**目标 50 条，当前通过 ${prompts.length} 条。缺口会保留，不会用虚构 Prompt 补齐。`,
  '',
  '每条记录都分开标注模型声明、引擎、原始或衍生指令、可见结果、原始来源、作者、核验日期与版权状态。“GPT-6 Astra”指来源所述工作流使用的模型，不代表 BeatAPI 自身提供原生 3D 渲染。',
  '',
  '## Prompt 合集',
  '',
  tableRows('zh'),
  '## 贡献',
  '',
  '请先阅读 [CONTRIBUTING.md](CONTRIBUTING.md)。新增条目必须提供公开来源、可复制 Prompt 或 Agent 指令、明确模型声明与可见结果。',
  '',
  '## 版权',
  '',
  'MIT 许可证只覆盖本仓库原创工具与编辑结构。来源 Prompt 和媒体保留各自原始权利，详见 [RIGHTS.md](RIGHTS.md)。',
  '',
].join('\n');

await rm(detailsDir, { recursive: true, force: true });
await mkdir(detailsDir, { recursive: true });
for (const item of prompts) {
  const body = [
    '<!-- Generated by scripts/generate.mjs. -->',
    '',
    `# ${item.title}`,
    '',
    `[View the result at its original source](${item.source.url})`,
    '',
    item.effect_summary,
    '',
    `- Model: ${item.model.label}`,
    `- Engine: ${item.engines.join(' + ') || 'Not specified in source'}`,
    `- Category: ${item.category}`,
    `- Fidelity: ${item.instruction.fidelity}`,
    `- Verified: ${item.verification.verified_at}`,
    `- Creator: [${item.source.author.name}](${item.source.url})`,
    `- Rights: ${item.rights.status}; preview and prompt retain source attribution`,
    '',
    '## Prompt',
    '',
    '```text',
    item.instruction.text,
    '```',
    '',
    '## Run it with GPT-6 Astra',
    '',
    '[Open GPT-6 Astra API](https://beatapi.io/gpt-6-astra-api?utm_source=github&utm_medium=detail&utm_campaign=awesome-3d-prompts)',
    '',
    '> BeatAPI provides model API access. The 3D application, MCP integration, assets, and rendering pipeline remain separate parts of the workflow.',
    '',
  ].join('\n');
  await writeFile(new URL(`details/${item.slug}.md`, root), body);
}

await writeFile(new URL('README.md', root), readme);
await writeFile(new URL('README.zh-CN.md', root), readmeZh);
